Repository credebl/studio, pull requests merged in 2025-05, with the labels that each got.

#971 refactor: table component lint
  nextjs/package.json
  nextjs/pnpm-lock.yaml
  nextjs/src/app/api/connection.ts
  nextjs/src/components/ui/generic-table-component/columns.tsx
  nextjs/src/components/ui/generic-table-component/data-table-column-header.tsx
  nextjs/src/components/ui/generic-table-component/data-table-faceted-filter.tsx
  nextjs/src/components/ui/generic-table-component/data-table-pagination.tsx
  nextjs/src/components/ui/generic-table-component/data-table-toolbar.tsx
  nextjs/src/components/ui/generic-table-component/data-table-view-options.tsx
  nextjs/src/components/ui/generic-table-component/data-table.tsx
  nextjs/src/features/connections/components/Connections.tsx
  nextjs/src/features/connections/types/connections-interface.ts
  nextjs/src/features/users/components/Members.tsx
Labels: enhancement

#966 refactor: Issuance API pages and routes
  nextjs/.eslintrc.js
  nextjs/package.json
  nextjs/pnpm-lock.yaml
  nextjs/src/app/api/Issuance.ts
  nextjs/src/app/api/schema.ts
  nextjs/src/app/organizations/credentials/connections/issuance/page.tsx
  nextjs/src/app/organizations/credentials/connections/page.tsx
  nextjs/src/app/organizations/credentials/issue/page.tsx
  nextjs/src/app/organizations/credentials/issue/schemas/page.tsx
  nextjs/src/app/organizations/credentials/page.tsx
  nextjs/src/common/enums.ts
Labels: refactor

#967 refactor: Added Issuance related components
  nextjs/src/components/EmptyListComponent.tsx
  nextjs/src/components/RoleViewButton.tsx
  nextjs/src/components/SearchInput.tsx
  nextjs/src/components/ShadCnSelect.tsx
  nextjs/src/components/SummaryCard.tsx
  nextjs/src/components/SummaryCardW3c.tsx
  nextjs/src/components/types/EmptyListComponent.ts
Labels: refactor

#969 Refactor/Issuance Dashboard page and types
  nextjs/src/features/organization/connectionIssuance/components/IssueDashboard.tsx
  nextjs/src/features/organization/connectionIssuance/components/connectionsTables/SortDataTable.tsx
  nextjs/src/features/organization/connectionIssuance/type/ConnectionIssueTable.ts
  nextjs/src/features/organization/connectionIssuance/type/Connections.ts
  nextjs/src/features/organization/connectionIssuance/type/CredDefSelection.ts
  nextjs/src/features/organization/connectionIssuance/type/Credentials.ts
  nextjs/src/features/organization/connectionIssuance/type/Dashboard.ts
  nextjs/src/features/organization/connectionIssuance/type/Issuance.ts
  nextjs/src/features/organization/connectionIssuance/type/SchemaCard.ts
  nextjs/src/features/organization/connectionIssuance/type/SchemasList.ts
Labels: refactor

#980 fix: issues on org dashboard and wallet creation
  nextjs/pnpm-lock.yaml
  nextjs/public/images/CREDEBL_Logo_Web.svg
  nextjs/public/images/CREDEBL_Logo_Web_Dark.svg
  nextjs/public/images/sovio_dark_theme_logo.svg
  nextjs/src/components/layout/app-sidebar.tsx
  nextjs/src/features/auth/components/SignUpViewPage.tsx
  nextjs/src/features/auth/components/UserInfoForm.tsx
  nextjs/src/features/auth/components/sigin-view.tsx
  nextjs/src/features/wallet/LedgerConfig.tsx
Labels: bug

#977 fix: Resolved issues related to type and eslint
  nextjs/src/app/organizations/credentials/issue/schemas/page.tsx
  nextjs/src/features/organization/connectionIssuance/components/ConnectionIssueTable.tsx
  nextjs/src/features/organization/connectionIssuance/components/ConnectionList.tsx
  nextjs/src/features/organization/connectionIssuance/components/Issuance.tsx
  nextjs/src/features/organization/connectionIssuance/components/connectionsTables/SortDataTable.tsx
Labels: bug

#981 Refactor / Added functionality for bulk issuance
  nextjs/package.json
  nextjs/pnpm-lock.yaml
  nextjs/src/app/api/BulkIssuance.ts
  nextjs/src/app/globals.css
  nextjs/src/app/organizations/credentials/issue/bulk-issuance/history/[requestId]/page.tsx
  nextjs/src/app/organizations/credentials/issue/bulk-issuance/history/page.tsx
  nextjs/src/app/organizations/credentials/issue/bulk-issuance/page.tsx
  nextjs/src/components/ShadCnSelect.tsx
  nextjs/src/components/ui/modal.tsx
  nextjs/src/features/organization/bulkIssuance/components/BulkIssuance.tsx
  nextjs/src/features/organization/bulkIssuance/components/BulkIssuanceFunctions.ts
  nextjs/src/features/organization/bulkIssuance/components/BulkIssuanceUtils.ts
  nextjs/src/features/organization/bulkIssuance/components/DragAndDrop.tsx
  nextjs/src/features/organization/bulkIssuance/components/History.tsx
  nextjs/src/features/organization/bulkIssuance/components/HistoryDetail.tsx
  nextjs/src/features/organization/bulkIssuance/components/IssuancePopup.tsx
  nextjs/src/features/organization/bulkIssuance/components/ResetIssue.tsx
  nextjs/src/features/organization/bulkIssuance/components/Steps.tsx
  nextjs/src/features/organization/bulkIssuance/components/Table.tsx
  nextjs/src/features/organization/bulkIssuance/type/BulkIssuance.tsx
  nextjs/src/lib/socketSlice.ts
  nextjs/src/lib/store.ts
Labels: refactor

#998 Fix the functionality to reset password
  nextjs/src/app/globals.css
  nextjs/src/app/reset-password/PasswordSuggestionBox.tsx
  nextjs/src/app/reset-password/ResetPassword.tsx
  nextjs/src/app/reset-password/page.tsx
  nextjs/src/components/PageLayout.tsx
  nextjs/src/config/CommonConstant.ts
  nextjs/src/config/pathRoutes.ts
  nextjs/src/config/svgs/PasswordSuggestion.tsx
  nextjs/src/config/svgs/ResetPassword.tsx
  nextjs/src/features/auth/components/user-auth-form.tsx
  nextjs/tailwind.config.js
Labels: bug
